package com.auction.common.protocol;

// Gson is the JSON library used throughout the project.
// It converts Java objects to/from JSON strings that travel over the TCP socket.
import com.google.gson.Gson;

// JsonElement is Gson's generic "any JSON value" type.
// We store the payload as JsonElement (not a raw String) so Gson can re-parse
// it later into the correct concrete type once we know the MessageType.
import com.google.gson.JsonElement;

// UUID generates a universally unique identifier for each message.
// This is used as requestId so the receiver can match a response to its request.
import java.util.UUID;

/**
 * FILE ROLE: The wire-format envelope for every message on the TCP connection.
 *
 * Every piece of data travelling between server and client is wrapped in a Message.
 * The JSON representation looks like:
 * <pre>
 * {
 *   "requestId": "550e8400-e29b-41d4-a716-446655440000",
 *   "type":      "PLACE_BID",
 *   "payload":   { "auctionId": 3, "amount": 250.0 }
 * }
 * </pre>
 *
 * REQUEST-RESPONSE CORRELATION:
 *   The client generates a UUID requestId and stores a CompletableFuture keyed by it.
 *   The server echoes the same requestId in its response.
 *   The client's reader thread looks up the future by requestId and completes it.
 *
 * SERVER-PUSH BROADCASTS:
 *   The server generates a brand-new UUID for broadcasts (bid events, auction end, etc.).
 *   Since no client future exists for this ID, the client's reader routes it to the
 *   registered BroadcastListener instead.
 *
 * WHY JsonElement PAYLOAD:
 *   We don't know the concrete payload type at deserialisation time — we only know it
 *   after reading the "type" field.  Storing it as JsonElement defers the final parse
 *   until the handler calls parsePayload(gson, ConcreteClass.class).
 */
public final class Message {

    // The correlation ID: generated by the sender, echoed by the responder.
    // Broadcasts carry a fresh ID that no client is waiting for.
    private String requestId;

    // Discriminates the payload type — both sides switch on this.
    private MessageType type;

    // The actual content, kept as a generic JSON tree until the receiver
    // knows which class to deserialise it into.
    private JsonElement payload;

    // ── Static factory methods (preferred over constructors) ─────────────────
    // We use factories instead of a public constructor so callers can't forget
    // to set fields, and so the naming makes intent explicit.

    /**
     * Build any outbound message (request or response).
     * A fresh UUID is generated automatically — callers never need to manage IDs.
     *
     * @param type       the action this message represents
     * @param payloadObj the Java object to serialise as the payload
     * @param gson       the shared Gson instance (thread-safe, so sharing is fine)
     */
    public static Message of(MessageType type, Object payloadObj, Gson gson) {
        Message m = new Message();
        m.requestId = UUID.randomUUID().toString(); // generates e.g. "550e8400-..."
        m.type = type;
        m.payload = gson.toJsonTree(payloadObj);    // converts Java object → JSON tree
        return m;
    }

    /**
     * Build a server-push broadcast.
     * Semantically identical to {@link #of} — a separate method exists only to make
     * the calling code self-documenting ("this is a broadcast, not a response").
     */
    public static Message broadcast(MessageType type, Object payloadObj, Gson gson) {
        return of(type, payloadObj, gson); // same construction, clearer name at call sites
    }

    /**
     * Build a reply that echoes the original requestId.
     * The server calls this so the client can match the response to the pending future.
     *
     * @param requestId the ID copied from the incoming request
     */
    public static Message reply(String requestId, MessageType type, Object payloadObj, Gson gson) {
        Message m = new Message();
        m.requestId = requestId;                    // echo the caller's ID, not a new one
        m.type = type;
        m.payload = gson.toJsonTree(payloadObj);
        return m;
    }

    // ── Accessors ─────────────────────────────────────────────────────────────

    /** Returns the correlation UUID so futures can be matched. */
    public String getRequestId() { return requestId; }

    /** Returns the action type so handlers can switch on it. */
    public MessageType getType() { return type; }

    /** Returns the raw JSON payload tree. */
    public JsonElement getPayload() { return payload; }

    /**
     * Deserialise the payload into a specific Java class.
     * Called by handlers once they know the MessageType and therefore the class.
     *
     * Example:
     *   PlaceBidRequest req = msg.parsePayload(gson, PlaceBidRequest.class);
     *
     * @param gson  the Gson instance (must be the same one used to serialise)
     * @param clazz the target class to deserialise into
     */
    public <T> T parsePayload(Gson gson, Class<T> clazz) {
        return gson.fromJson(payload, clazz);
    }

    @Override
    public String toString() {
        return "Message{requestId='" + requestId + "', type=" + type + '}';
    }
}
